import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/Components/SideNavBar";
import Navbar from "@/Components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <div className="flex flex-col sm:flex-row">
        <SideNavbar />
        <div className="flex-1 w-full sm:ml-50 md:ml-64 transition-all duration-300">
          <Navbar />
          <main className="p-4 sm:p-6 md:p-8">{children}</main>
        </div>
      </div>
    </body>
  </html>
  );
}
